"use client";

import { useEffect, useRef, useState } from "react";
import { Camera, FileText, ImagePlus, Plus, X, ArrowUp, ChevronUp, Search, BookOpen, Code2, Eye, PenLine, Sparkles } from "lucide-react";
import { THEON_MODES, type TheonMode } from "@/lib/theon-modes";

export type SelectedFeature = { id: string; label: string; hint: string };
export type Attachment = { name: string; type: string; dataUrl: string; extractedText?: string };
type Props = { feature: SelectedFeature | null; value: string; onChange: (value: string) => void; onSend: (attachments: Attachment[]) => void; onClearFeature: () => void; mode: TheonMode; onModeChange: (mode: TheonMode) => void; disabled?: boolean };
const MAX_IMAGE_DATA_URL_LENGTH = 3_000_000;
const MAX_IMAGE_DIMENSION = 1600;
const MAX_PDF_SIZE = 6 * 1024 * 1024;
const MAX_PDF_TEXT = 120_000;

async function compressImage(file: File): Promise<Attachment> {
  if (file.type === "image/heic" || file.type === "image/heif") throw new Error("This camera format isn't supported. Please use JPG or PNG.");
  const sourceUrl = URL.createObjectURL(file);
  try { const image = new Image(); image.decoding = "async"; image.src = sourceUrl; await image.decode(); const scale = Math.min(1, MAX_IMAGE_DIMENSION / Math.max(image.naturalWidth, image.naturalHeight)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(image.naturalWidth * scale)); canvas.height = Math.max(1, Math.round(image.naturalHeight * scale)); const context = canvas.getContext("2d"); if (!context) throw new Error("Image processing is unavailable on this device"); context.drawImage(image, 0, 0, canvas.width, canvas.height); let quality = 0.82; let dataUrl = canvas.toDataURL("image/jpeg", quality); while (dataUrl.length > MAX_IMAGE_DATA_URL_LENGTH && quality > 0.5) { quality -= 0.08; dataUrl = canvas.toDataURL("image/jpeg", quality); } return { name: file.name, type: "image/jpeg", dataUrl }; }
  finally { URL.revokeObjectURL(sourceUrl); }
}
async function extractPdfText(file: File): Promise<Attachment> {
  if (file.size > MAX_PDF_SIZE) throw new Error("PDF is too large. Please upload a PDF smaller than 6 MB.");
  const bytes = new Uint8Array(await file.arrayBuffer()); const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); const pdfVersion = String(pdfjs.version || "5.4.54"); pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfVersion}/pdf.worker.min.mjs`; const pdf = await pdfjs.getDocument({ data: bytes }).promise; let text = "";
  for (let pageNumber = 1; pageNumber <= pdf.numPages && text.length < MAX_PDF_TEXT; pageNumber += 1) { const page = await pdf.getPage(pageNumber); const content = await page.getTextContent(); const pageText = content.items.map((item: any) => typeof item?.str === "string" ? item.str : "").join(" ").replace(/\s+/g, " ").trim(); if (pageText) text += `\n\n--- Page ${pageNumber} ---\n${pageText}`; page.cleanup(); }
  text = text.trim().slice(0, MAX_PDF_TEXT); if (!text) throw new Error("This PDF appears to be scanned/image-only. Text could not be extracted yet."); return { name: file.name, type: "application/pdf", dataUrl: "", extractedText: text };
}
export async function processAttachmentFiles(files: File[]): Promise<Attachment[]> { return Promise.all(files.slice(0, 4).map((file) => file.type === "application/pdf" ? extractPdfText(file) : compressImage(file))); }
const modeIcons = { chat: Sparkles, web: Search, research: Search, study: BookOpen, code: Code2, vision: Eye, write: PenLine };

export default function FeatureInput({ feature, value, onChange, onSend, onClearFeature, mode, onModeChange, disabled = false }: Props) {
  const galleryRef = useRef<HTMLInputElement>(null); const cameraRef = useRef<HTMLInputElement>(null); const pdfRef = useRef<HTMLInputElement>(null); const pickerRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null); const [attachments, setAttachments] = useState<Attachment[]>([]); const [processing, setProcessing] = useState(false); const [error, setError] = useState(""); const [showPicker, setShowPicker] = useState(false); const [showModes, setShowModes] = useState(false);
  useEffect(() => { if (!showPicker && !showModes) return; const close = (event: PointerEvent) => { if (pickerRef.current && !pickerRef.current.contains(event.target as Node)) { setShowPicker(false); setShowModes(false); } }; document.addEventListener("pointerdown", close); return () => document.removeEventListener("pointerdown", close); }, [showPicker, showModes]);
  async function addFiles(files: FileList | null) { if (!files) return; setError(""); setShowPicker(false); const accepted = Array.from(files).slice(0, 4); if (!accepted.length) return; setProcessing(true); try { const next = await processAttachmentFiles(accepted); setAttachments((current) => [...current, ...next].slice(0, 4)); requestAnimationFrame(() => inputRef.current?.focus({ preventScroll: true })); } catch (e) { console.error(e); setError(e instanceof Error ? e.message : "Could not process the attachment."); } finally { setProcessing(false); } }
  function sendAttachments() { if (!canSend || processing) return; const pending = attachments; setAttachments([]); onSend(pending); }
  const canSend = !disabled && !processing && (value.trim().length > 0 || attachments.length > 0);
  const ModeIcon = modeIcons[mode];
  const suggestions = mode === "study" ? ["Explain this simply", "Make me a quiz", "Create revision notes"] : mode === "research" ? ["Compare the latest sources", "Find primary sources", "Give me the key findings"] : mode === "code" ? ["Find bugs", "Explain this code", "Improve it"] : ["Explain simply", "Give examples", "Go deeper"];
  return <div ref={pickerRef} className="fixed bottom-[max(10px,env(safe-area-inset-bottom))] left-3 right-3 z-30 lg:hidden" onPointerDown={(event) => event.stopPropagation()} onTouchStart={(event) => event.stopPropagation()}>
    {feature && <div className="mb-2 flex items-center gap-2 rounded-2xl border border-violet-400/20 bg-[#0b0b0b]/95 px-3 py-2.5 shadow-[0_10px_35px_rgba(0,0,0,.5)] backdrop-blur-xl"><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-medium text-white/90">{feature.label}</p><p className="truncate text-[10px] text-white/35">{feature.hint}</p></div><button type="button" onClick={onClearFeature} aria-label="Change feature" className="flex h-7 w-7 items-center justify-center rounded-full text-white/45 hover:bg-white/10 hover:text-white"><X size={15}/></button></div>}
    {error && <div className="mb-2 rounded-2xl border border-red-400/20 bg-red-500/[.06] px-3 py-2 text-[11px] text-red-200" role="alert">{error}</div>}
    {attachments.length > 0 && <div className="mb-2 flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#090909]/95 p-2">{attachments.map((file, index) => <button key={`${file.name}-${index}`} type="button" onClick={() => setAttachments((items) => items.filter((_, i) => i !== index))} aria-label={`Remove ${file.name}`} className="flex h-11 max-w-[180px] shrink-0 items-center gap-1.5 rounded-xl border border-white/10 bg-white/[.04] px-2 text-left text-[10px] text-white/70">{file.type.startsWith("image/") ? <ImagePlus size={15}/> : <FileText size={15}/>}<span className="truncate">{file.type === "application/pdf" ? "PDF" : "Image"}</span><X size={12}/></button>)}</div>}
    {showModes && <div className="mb-2 rounded-2xl border border-white/10 bg-[#0b0b0b]/98 p-2 shadow-[0_10px_35px_rgba(0,0,0,.65)] backdrop-blur-2xl"><div className="grid grid-cols-2 gap-1">{THEON_MODES.map((item) => { const Icon = modeIcons[item.id]; return <button key={item.id} type="button" onClick={() => { onModeChange(item.id); setShowModes(false); requestAnimationFrame(() => inputRef.current?.focus({ preventScroll: true })); }} className={`flex items-center gap-2 rounded-xl px-3 py-2.5 text-left ${mode === item.id ? "bg-white/[.08] text-white" : "text-white/55 hover:bg-white/[.05]"}`}><Icon size={15}/><span><span className="block text-[11px] font-medium">{item.label}</span><span className="block text-[8px] text-white/25">{item.description}</span></span></button>; })}</div></div>}
    {showPicker && <div className="mb-2 grid grid-cols-3 gap-2 rounded-2xl border border-white/10 bg-[#0b0b0b]/98 p-2 shadow-[0_10px_35px_rgba(0,0,0,.6)]"><button type="button" onClick={() => cameraRef.current?.click()} className="flex flex-col items-center gap-1.5 rounded-xl px-2 py-3 text-[10px] text-white/70 hover:bg-white/[.06]"><Camera size={20}/><span>Camera</span></button><button type="button" onClick={() => galleryRef.current?.click()} className="flex flex-col items-center gap-1.5 rounded-xl px-2 py-3 text-[10px] text-white/70 hover:bg-white/[.06]"><ImagePlus size={20}/><span>Gallery</span></button><button type="button" onClick={() => pdfRef.current?.click()} className="flex flex-col items-center gap-1.5 rounded-xl px-2 py-3 text-[10px] text-white/70 hover:bg-white/[.06]"><FileText size={20}/><span>PDF</span></button></div>}
    <input ref={cameraRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={(e) => { void addFiles(e.target.files); e.currentTarget.value=""; }}/><input ref={galleryRef} type="file" accept="image/*" multiple className="hidden" onChange={(e) => { void addFiles(e.target.files); e.currentTarget.value=""; }}/><input ref={pdfRef} type="file" accept="application/pdf,.pdf" multiple className="hidden" onChange={(e) => { void addFiles(e.target.files); e.currentTarget.value=""; }}/>
    <div className="mb-1 flex items-center justify-between px-2"><button type="button" onClick={() => setShowModes((v) => !v)} className="flex items-center gap-1.5 rounded-full border border-white/[.09] bg-white/[.035] px-2.5 py-1 text-[9px] text-white/50 backdrop-blur-xl"><ModeIcon size={11}/>{THEON_MODES.find((item) => item.id === mode)?.label}<ChevronUp size={10}/></button><div className="flex gap-1 overflow-x-auto">{suggestions.map((suggestion) => <button key={suggestion} type="button" onClick={() => { onChange(suggestion); requestAnimationFrame(() => inputRef.current?.focus({ preventScroll: true })); }} className="shrink-0 rounded-full border border-white/[.07] bg-white/[.025] px-2 py-1 text-[8px] text-white/30 hover:text-white/65">{suggestion}</button>)}</div></div>
    <form onSubmit={(event) => { event.preventDefault(); event.stopPropagation(); sendAttachments(); }} noValidate autoComplete="off" className="relative flex min-h-[60px] items-center gap-2 rounded-[28px] border border-white/[0.12] bg-black px-1.5 py-1.5 shadow-[0_12px_40px_rgba(0,0,0,.65)]">
      <button type="button" onClick={() => setShowPicker((open) => !open)} disabled={disabled || processing} aria-label="Add attachment" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-white/[.10] bg-white/[.035] text-white/75 active:scale-95 disabled:opacity-40"><Plus size={22} strokeWidth={1.7}/></button>
      <input ref={inputRef} value={value} onChange={(e) => onChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendAttachments(); } }} onPointerDown={(e) => e.stopPropagation()} onTouchStart={(e) => e.stopPropagation()} type="text" enterKeyHint="send" autoComplete="off" autoCorrect="on" autoCapitalize="sentences" spellCheck={true} placeholder={processing ? "Reading PDF..." : feature ? "Add context for Theon..." : mode === "web" ? "Search the web with Theon..." : mode === "research" ? "Ask for deep research..." : "Ask Theon anything..."} disabled={disabled || processing} className="h-11 min-w-0 flex-1 bg-transparent px-1 text-[15px] text-white outline-none placeholder:text-white/30"/>
      <button type="submit" disabled={!canSend} aria-label="Send message" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-violet-600 via-purple-500 to-cyan-400 text-black disabled:opacity-35"><ArrowUp size={21}/></button>
    </form>
    {attachments.length > 0 && <p className="mt-1.5 text-center text-[9px] text-white/25">🔒 Images and PDFs are temporary and are deleted after this analysis. They aren&apos;t saved to your chat history.</p>}
  </div>;
}
