"use client";

import { BookOpen, LogOut, MessageSquare, Pencil, Plus, Search, Settings, User, X, Trash2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ChatSummary } from "@/lib/chat-history";

type Props = { open: boolean; onClose: () => void; chats: ChatSummary[]; currentChatId: string | null; onNewChat: () => void; onSelectChat: (id: string) => void; onDeleteChat: (id: string) => void; onRenameChat: (id: string, title: string) => void; onProfile?: () => void; onSettings?: () => void; onLogout: () => void };

export default function MobileSidebar({ open, onClose, chats, currentChatId, onNewChat, onSelectChat, onDeleteChat, onRenameChat, onProfile = () => { window.location.href = "/profile"; }, onSettings = () => { window.location.href = "/settings"; }, onLogout }: Props) {
  const [managedChat, setManagedChat] = useState<ChatSummary | null>(null); const [query, setQuery] = useState(""); const longPressTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (longPressTimer.current) clearTimeout(longPressTimer.current); }, []);
  const filtered = useMemo(() => chats.filter((chat) => `${chat.title} ${chat.preview || ""}`.toLowerCase().includes(query.toLowerCase())), [chats, query]);
  function startLongPress(chat: ChatSummary) { if (longPressTimer.current) clearTimeout(longPressTimer.current); longPressTimer.current = setTimeout(() => setManagedChat(chat), 520); }
  function cancelLongPress() { if (longPressTimer.current) { clearTimeout(longPressTimer.current); longPressTimer.current = null; } }
  function select(chat: ChatSummary) { onClose(); if (chat.kind === "study") { window.location.href = `/study?chat=${encodeURIComponent(chat.id)}`; return; } onSelectChat(chat.id); }
  function handleRename() { if (!managedChat) return; const nextTitle = window.prompt("Rename conversation", managedChat.title); if (nextTitle?.trim()) onRenameChat(managedChat.id, nextTitle.trim()); setManagedChat(null); }
  function handleDelete() { if (!managedChat) return; const confirmed = window.confirm(`Delete “${managedChat.title}”? This cannot be undone.`); if (confirmed) onDeleteChat(managedChat.id); setManagedChat(null); }
  return <>
    <div onClick={onClose} className={`fixed inset-0 z-40 bg-black/60 backdrop-blur-md transition-opacity duration-100 ${open ? "visible opacity-100" : "invisible opacity-0"}`}/>
    <aside aria-hidden={!open} className={`fixed left-0 top-0 z-50 flex h-[100dvh] w-[86%] max-w-[340px] flex-col overflow-hidden border-r border-white/[0.12] bg-white/[0.045] shadow-[20px_0_80px_rgba(0,0,0,.5),inset_-1px_0_0_rgba(255,255,255,.04)] backdrop-blur-3xl transition-transform duration-100 ease-out ${open ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="pointer-events-none absolute -left-20 top-10 h-48 w-48 rounded-full bg-violet-500/[0.12] blur-[70px]"/><div className="pointer-events-none absolute -right-20 bottom-24 h-56 w-56 rounded-full bg-cyan-400/[0.07] blur-[80px]"/>
      <div className="relative flex items-center justify-end border-b border-white/[0.09] bg-white/[0.025] px-4 py-4"><button onClick={onClose} className="flex h-9 w-9 items-center justify-center rounded-full border border-white/[0.08] bg-white/[0.04] text-white/55 transition-colors hover:bg-white/[0.09]"><X size={19}/></button></div>
      <div className="relative p-4"><button onClick={onNewChat} className="flex h-12 w-full items-center justify-center gap-2.5 rounded-2xl border border-white/[0.12] bg-gradient-to-r from-violet-600/90 to-cyan-500/80 text-sm font-semibold text-white shadow-[0_12px_35px_rgba(124,58,237,.22)] backdrop-blur-xl transition-transform active:scale-[.985]"><Plus size={19}/> New chat</button></div>
      <div className="relative px-4"><div className="mb-3 flex items-center gap-2 rounded-2xl border border-white/[0.1] bg-white/[0.045] px-3.5 py-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,.04)] backdrop-blur-xl"><Search size={15} className="text-white/30"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search conversations" className="min-w-0 flex-1 bg-transparent text-xs text-white outline-none placeholder:text-white/30"/></div></div>
      <div className="relative flex-1 overflow-y-auto px-4"><p className="mb-2 px-2 text-[10px] font-medium uppercase tracking-[.18em] text-white/30">Chat history</p>{filtered.length === 0 ? <p className="px-2 py-3 text-xs text-white/30">{query ? "No matching conversations." : "No conversations yet."}</p> : <div className="space-y-1.5">{filtered.map((chat) => <button key={chat.id} type="button" onClick={() => select(chat)} onContextMenu={(e) => { e.preventDefault(); setManagedChat(chat); }} onTouchStart={() => startLongPress(chat)} onTouchEnd={cancelLongPress} onTouchMove={cancelLongPress} className={`group flex w-full min-w-0 items-center gap-3 rounded-2xl border px-3.5 py-3 text-left transition-all duration-100 ${currentChatId === chat.id ? "border-violet-300/[0.16] bg-white/[0.09] shadow-[inset_0_1px_0_rgba(255,255,255,.05)]" : "border-transparent hover:border-white/[0.06] hover:bg-white/[0.045]"}`}>{chat.kind === "study" ? <BookOpen size={16} className="shrink-0 text-violet-300/70"/> : <MessageSquare size={16} className="shrink-0 text-white/45"/>}<span className="min-w-0 flex-1"><span className="flex items-center gap-1.5 truncate"><span className="truncate text-[13px] text-white/80">{chat.title}</span>{chat.kind === "study" && <span className="shrink-0 rounded-full bg-violet-400/10 px-1.5 py-0.5 text-[8px] uppercase tracking-wider text-violet-300/70">Study</span>}</span>{chat.preview && <span className="mt-0.5 block truncate text-[10px] text-white/30">{chat.preview}</span>}</span></button>)}</div>}</div>
      <div className="relative space-y-1 border-t border-white/[0.09] bg-white/[0.02] p-4 backdrop-blur-xl"><button onClick={onProfile} className="flex w-full items-center gap-3 rounded-2xl border border-transparent px-3 py-3 text-sm text-white/55 transition-colors hover:border-white/[0.06] hover:bg-white/[0.045]"><User size={18}/> Profile</button><button onClick={onSettings} className="flex w-full items-center gap-3 rounded-2xl border border-transparent px-3 py-3 text-sm text-white/55 transition-colors hover:border-white/[0.06] hover:bg-white/[0.045]"><Settings size={18}/> Settings</button><button onClick={onLogout} className="flex w-full items-center gap-3 rounded-2xl border border-transparent px-3 py-3 text-sm text-red-300/75 transition-colors hover:border-red-300/[0.08] hover:bg-red-500/[0.07]"><LogOut size={18}/> Logout</button></div>
    </aside>
    {managedChat && <div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/60 px-3 pb-4 backdrop-blur-md sm:items-center" onClick={() => setManagedChat(null)}><div className="relative w-full max-w-sm overflow-hidden rounded-3xl border border-white/[0.12] bg-white/[0.07] p-4 shadow-[0_24px_80px_rgba(0,0,0,.5)] backdrop-blur-3xl" onClick={(e) => e.stopPropagation()}><div className="pointer-events-none absolute -right-12 -top-12 h-28 w-28 rounded-full bg-violet-500/[0.12] blur-3xl"/><p className="relative px-2 text-[11px] uppercase tracking-[.16em] text-white/35">Manage conversation</p><p className="relative mt-1 truncate px-2 text-sm font-medium text-white/90">{managedChat.title}</p><button onClick={handleRename} className="mt-4 flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-left text-sm text-white/75 hover:bg-white/[.07]"><Pencil size={17}/> Rename</button><button onClick={handleDelete} className="flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-left text-sm text-red-200 hover:bg-red-500/[.08]"><Trash2 size={17}/> Delete conversation</button><button onClick={() => setManagedChat(null)} className="mt-1 w-full rounded-2xl px-4 py-3 text-sm text-white/40">Cancel</button></div></div>}
  </>;
}
