"use client";

import { useEffect, useRef, useState } from "react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import MobileLayout from "@/components/mobile/MobileLayout";
import MobileHeader from "@/components/mobile/MobileHeader";
import MobileWelcome from "@/components/mobile/MobileWelcome";
import FeatureInput, { type Attachment, type SelectedFeature } from "@/components/mobile/FeatureInput";
import DesktopComposer from "@/components/DesktopComposer";
import MobileSidebar from "@/components/mobile/MobileSidebar";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import ChatBubble from "@/components/ChatBubble";
import TypingIndicator from "@/components/TypingIndicator";
import LogoFormation from "@/components/LogoFormation";
import { auth } from "@/lib/firebase";
import { createChat, deleteChat, loadChats, loadMessages, migrateLegacyMessages, renameChat, saveMessage, updateChatPreview, type ChatMessage, type ChatSummary } from "@/lib/chat-history";

type Message = Pick<ChatMessage, "role" | "text"> & { attachments?: Attachment[] };
type Preferences = { enterToSend: boolean; autoScroll: boolean; speed: "fast" | "normal"; style: "balanced" | "concise" | "detailed"; explanation: "simple" | "normal" | "deep"; language: "auto" | "english" | "marathi" | "hindi" };
const defaultPreferences: Preferences = { enterToSend: true, autoScroll: true, speed: "fast", style: "balanced", explanation: "normal", language: "auto" };
function makeTitle(text: string) { const clean = text.replace(/\s+/g, " ").trim(); return clean.length > 48 ? `${clean.slice(0, 48)}…` : clean || "New chat"; }
function sortChats(chats: ChatSummary[]) { return [...chats].sort((a, b) => { const aTime = a.updatedAt && typeof a.updatedAt === "object" && "toMillis" in a.updatedAt ? (a.updatedAt as { toMillis: () => number }).toMillis() : 0; const bTime = b.updatedAt && typeof b.updatedAt === "object" && "toMillis" in b.updatedAt ? (b.updatedAt as { toMillis: () => number }).toMillis() : 0; return bTime - aTime; }); }

export default function Home() {
  const router = useRouter(); const [message, setMessage] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [isTyping, setIsTyping] = useState(false); const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false); const [chats, setChats] = useState<ChatSummary[]>([]); const [currentChatId, setCurrentChatId] = useState<string | null>(null); const [userReady, setUserReady] = useState(false); const [logoFormationKey, setLogoFormationKey] = useState(0); const [selectedFeature, setSelectedFeature] = useState<SelectedFeature | null>(null); const [preferences, setPreferences] = useState<Preferences>(defaultPreferences);
  const chatRef = useRef<HTMLDivElement>(null); const animationFrameRef = useRef<number | null>(null);
  useEffect(() => { try { const saved = localStorage.getItem("theon-settings"); if (saved) setPreferences({ ...defaultPreferences, ...JSON.parse(saved) }); } catch {} }, []);
  useEffect(() => { let active = true; const unsubscribe = onAuthStateChanged(auth, async (user) => { if (!user) { router.replace("/login"); return; } setLogoFormationKey((key) => key + 1); try { let loadedChats = await loadChats(user.uid); if (loadedChats.length === 0) { const migratedId = await migrateLegacyMessages(user.uid); if (migratedId) loadedChats = await loadChats(user.uid); } if (!active) return; setChats(sortChats(loadedChats)); if (loadedChats.length > 0) { const firstChat = loadedChats[0]; setCurrentChatId(firstChat.id); const loadedMessages = await loadMessages(user.uid, firstChat.id); if (!active) return; setMessages(loadedMessages.map(({ role, text }) => ({ role, text }))); } else { setMessages([]); setCurrentChatId(null); } } catch (error) { console.error("Failed to load chat history", error); } finally { if (active) setUserReady(true); } }); return () => { active = false; unsubscribe(); if (animationFrameRef.current !== null) cancelAnimationFrame(animationFrameRef.current); }; }, [router]);
  useEffect(() => { if (preferences.autoScroll && (messages.length > 0 || isTyping)) chatRef.current?.scrollTo({ top: chatRef.current.scrollHeight, behavior: "smooth" }); }, [messages, isTyping, preferences.autoScroll]);
  async function startNewChat() { const user = auth.currentUser; if (!user || isTyping) return; try { const id = await createChat(user.uid); setChats((prev) => [{ id, title: "New chat", preview: "" }, ...prev]); setCurrentChatId(id); setMessages([]); setMessage(""); setSelectedFeature(null); setMobileSidebarOpen(false); setLogoFormationKey((key) => key + 1); } catch (error) { console.error("Failed to create chat", error); } }
  async function selectChat(id: string) { const user = auth.currentUser; if (!user || isTyping) return; setMobileSidebarOpen(false); setSelectedFeature(null); try { const loadedMessages = await loadMessages(user.uid, id); setCurrentChatId(id); setMessages(loadedMessages.map(({ role, text }) => ({ role, text }))); } catch (error) { console.error("Failed to load chat", error); } }
  async function removeChat(id: string) { const user = auth.currentUser; if (!user || isTyping) return; try { await deleteChat(user.uid, id); const remaining = chats.filter((chat) => chat.id !== id); setChats(remaining); if (currentChatId === id) { const next = remaining[0]; if (next) { setCurrentChatId(next.id); const loaded = await loadMessages(user.uid, next.id); setMessages(loaded.map(({ role, text }) => ({ role, text }))); } else { setCurrentChatId(null); setMessages([]); } } } catch (error) { console.error("Failed to delete chat", error); } }
  async function renameConversation(id: string, title: string) { const user = auth.currentUser; if (!user || isTyping) return; try { const cleanTitle = title.replace(/\s+/g, " ").trim().slice(0, 80); if (!cleanTitle) return; await renameChat(user.uid, id, cleanTitle); setChats((prev) => prev.map((chat) => chat.id === id ? { ...chat, title: cleanTitle } : chat)); } catch (error) { console.error("Failed to rename chat", error); } }
  function animateResponse(fullText: string) { const words = fullText.split(/(\s+)/); const wordsPerSecond = preferences.speed === "normal" ? 45 : 70; const startedAt = performance.now(); setMessages((prev) => [...prev, { role: "ai", text: "" }]); const frame = (now: number) => { const visibleWords = Math.min(words.length, Math.floor(((now - startedAt) / 1000) * wordsPerSecond)); const visibleText = words.slice(0, visibleWords).join(""); setMessages((prev) => { const next = [...prev]; if (next.length) next[next.length - 1] = { role: "ai", text: visibleText }; return next; }); if (visibleWords < words.length) animationFrameRef.current = requestAnimationFrame(frame); else { animationFrameRef.current = null; setIsTyping(false); } }; animationFrameRef.current = requestAnimationFrame(frame); }
  async function sendMessage(attachments: Attachment[] = []) { const user = auth.currentUser; const userText = message.trim(); if (!user || (!userText && attachments.length === 0) || isTyping || !userReady) return; setMessage(""); const activeFeature = selectedFeature; setSelectedFeature(null); const previousMessages = messages; let chatId = currentChatId; const firstMessage = !chatId || previousMessages.length === 0; const attachmentLabel = attachments.length === 1 ? (attachments[0].type.startsWith("image/") ? "Image" : "PDF") : `${attachments.length} attachments`; const historyText = userText || attachmentLabel; try { if (!chatId) { chatId = await createChat(user.uid, makeTitle(historyText)); setCurrentChatId(chatId); setChats((prev) => [{ id: chatId as string, title: makeTitle(historyText), preview: historyText }, ...prev]); } else if (firstMessage) { await updateChatPreview(user.uid, chatId, historyText, makeTitle(userText || historyText)); setChats((prev) => prev.map((chat) => chat.id === chatId ? { ...chat, title: makeTitle(userText || historyText), preview: historyText } : chat)); } const activeChatId = chatId; if (!activeChatId) throw new Error("Unable to create or select a chat"); await saveMessage(user.uid, activeChatId, "user", historyText); setMessages((prev) => [...prev, { role: "user", text: userText, attachments: attachments.map(({ name, type }) => ({ name, type, dataUrl: "" })) }]); setIsTyping(true); const res = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: userText, history: previousMessages, featureId: activeFeature?.id ?? null, attachments, preferences }) }); const data = await res.json().catch(() => ({})); if (!res.ok || typeof data.reply !== "string") throw new Error(data.error || "AI request failed"); const fullText = data.reply.trim(); await saveMessage(user.uid, activeChatId, "ai", fullText); setChats((prev) => { const existing = prev.find((chat) => chat.id === activeChatId); const updated: ChatSummary = existing ? { ...existing, preview: fullText } : { id: activeChatId, title: makeTitle(historyText), preview: fullText }; return [updated, ...prev.filter((chat) => chat.id !== activeChatId)]; }); animateResponse(fullText); } catch (error) { console.error("Chat error", error); setIsTyping(false); setMessages((prev) => [...prev, { role: "ai", text: "I couldn't complete that request. Please try again." }]); } }
  async function logout() { try { await signOut(auth); router.replace("/login"); } catch (error) { console.error("Logout failed", error); } }
  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>, send: () => void) => { if (e.key === "Enter" && !e.shiftKey && preferences.enterToSend) { e.preventDefault(); send(); } };
  return <>{userReady && <LogoFormation playKey={logoFormationKey}/>}<div className="tablet-mobile-shell lg:hidden h-[100dvh] w-screen overflow-hidden"><MobileLayout><MobileHeader onMenu={() => setMobileSidebarOpen(true)} onSettings={() => router.push("/settings")} /><div ref={chatRef} className={`min-h-0 flex-1 ${messages.length === 0 && !selectedFeature ? "overflow-hidden" : "overflow-y-auto overscroll-contain pb-24"}`}>{messages.length === 0 && !selectedFeature ? <MobileWelcome onFeatureSelect={setSelectedFeature}/> : messages.length === 0 ? <div className="h-full bg-black"/> : <div className="flex flex-col gap-5 px-4 pt-6 pb-36">{messages.map((msg, index) => <ChatBubble key={`${msg.role}-${index}`} role={msg.role} text={msg.text} attachments={msg.attachments}/>) }{isTyping && messages[messages.length - 1]?.role === "user" && <TypingIndicator/>}</div>}</div><FeatureInput feature={selectedFeature} value={message} onChange={setMessage} onSend={sendMessage} onClearFeature={() => setSelectedFeature(null)} disabled={!userReady || isTyping}/><MobileSidebar open={mobileSidebarOpen} onClose={() => setMobileSidebarOpen(false)} chats={chats} currentChatId={currentChatId} onNewChat={startNewChat} onSelectChat={selectChat} onDeleteChat={removeChat} onRenameChat={renameConversation} onLogout={logout}/></MobileLayout></div><main className="hidden h-[100dvh] min-h-0 overflow-hidden bg-black lg:flex lg:flex-row"><div className="hidden h-full shrink-0 lg:block lg:w-[264px]"><Sidebar onNewChat={startNewChat} chats={chats} currentChatId={currentChatId} onSelectChat={selectChat} onDeleteChat={removeChat}/></div><section className="flex min-h-0 min-w-0 flex-1 flex-col bg-black"><Header/><div ref={chatRef} className={`min-h-0 flex-1 overflow-y-auto overscroll-contain px-4 py-6 sm:px-6 lg:px-10 ${messages.length === 0 ? "overflow-hidden" : ""}`}><div className="mx-auto w-full max-w-4xl">{messages.length === 0 ? <div className="h-full min-h-0">{selectedFeature ? <div className="flex h-full items-end justify-center pb-8"><div className="w-full max-w-xl rounded-2xl border border-violet-400/20 bg-white/[.025] p-4 text-center text-sm text-white/70">{selectedFeature.label}<button onClick={() => setSelectedFeature(null)} className="ml-3 text-white/35 hover:text-white">Change</button></div></div> : <MobileWelcome onFeatureSelect={setSelectedFeature}/>}</div> : <div className="space-y-6">{messages.map((msg, index) => <ChatBubble key={`${msg.role}-${index}`} role={msg.role} text={msg.text} attachments={msg.attachments}/>) }{isTyping && messages[messages.length - 1]?.role === "user" && <TypingIndicator/>}</div>}</div></div><footer className="shrink-0 border-t border-white/[.08] bg-black px-4 py-4 sm:px-6 lg:px-10"><DesktopComposer feature={selectedFeature} value={message} onChange={setMessage} onSend={sendMessage} onClearFeature={() => setSelectedFeature(null)} disabled={!userReady || isTyping}/></footer></section></main></>;
}