"use client";

import { useEffect, useRef, useState } from "react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import MobileLayout from "@/components/mobile/MobileLayout";
import MobileHeader from "@/components/mobile/MobileHeader";
import MobileWelcome from "@/components/mobile/MobileWelcome";
import FeatureInput, { type Attachment, type SelectedFeature } from "@/components/mobile/FeatureInput";
import DesktopComposer from "@/components/DesktopComposer";
import MobileSidebar from "@/components/mobile/MobileSidebar";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import ChatBubble from "@/components/ChatBubble";
import TypingIndicator from "@/components/TypingIndicator";
import LogoFormation from "@/components/LogoFormation";
import { auth } from "@/lib/firebase";
import { cleanupEmptyChats, createChat, deleteChat, loadChats, loadMessages, migrateLegacyMessages, renameChat, saveMessage, updateChatPreview, type ChatMessage, type ChatSummary } from "@/lib/chat-history";
import type { TheonMode } from "@/lib/theon-modes";

type Source = { title: string; url: string; domain: string };
type Message = Pick<ChatMessage, "role" | "text"> & { attachments?: Attachment[]; sources?: Source[] };
type Preferences = { enterToSend: boolean; autoScroll: boolean; speed: "fast" | "normal"; style: "balanced" | "concise" | "detailed"; explanation: "simple" | "normal" | "deep"; language: "auto" | "english" | "marathi" | "hindi" };
const defaultPreferences: Preferences = { enterToSend: true, autoScroll: true, speed: "fast", style: "balanced", explanation: "normal", language: "auto" };
function makeTitle(text: string) { const clean = text.replace(/\s+/g, " ").trim(); return clean.length > 48 ? `${clean.slice(0, 48)}…` : clean || "New chat"; }
function sortChats(chats: ChatSummary[]) { return [...chats].sort((a, b) => { const get = (v: any) => v && typeof v === "object" && "toMillis" in v && typeof v.toMillis === "function" ? v.toMillis() : 0; return get(b.updatedAt) - get(a.updatedAt) || get(b.createdAt) - get(a.createdAt); }); }

export default function Home() {
  const router = useRouter(); const [message, setMessage] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [isTyping, setIsTyping] = useState(false); const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false); const [chats, setChats] = useState<ChatSummary[]>([]); const [currentChatId, setCurrentChatId] = useState<string | null>(null); const [userReady, setUserReady] = useState(false); const [logoFormationKey, setLogoFormationKey] = useState(0); const [selectedFeature, setSelectedFeature] = useState<SelectedFeature | null>(null); const [preferences, setPreferences] = useState<Preferences>(defaultPreferences); const [lastError, setLastError] = useState<string | null>(null); const [mode, setMode] = useState<TheonMode>("chat");
  const chatRef = useRef<HTMLDivElement>(null); const animationFrameRef = useRef<number | null>(null);
  useEffect(() => { try { const saved = localStorage.getItem("theon-settings"); if (saved) setPreferences({ ...defaultPreferences, ...JSON.parse(saved) }); } catch {} }, []);
  useEffect(() => { let active = true; const unsubscribe = onAuthStateChanged(auth, async (user) => { if (!user) { router.replace("/login"); return; } setLogoFormationKey((key) => key + 1); try { await migrateLegacyMessages(user.uid); await cleanupEmptyChats(user.uid); const loadedChats = sortChats(await loadChats(user.uid)); if (!active) return; setChats(loadedChats); setCurrentChatId(null); setMessages([]); setSelectedFeature(null); setMode("chat"); } catch (error) { console.error("Failed to load chat history", error); } finally { if (active) setUserReady(true); } }); return () => { active = false; unsubscribe(); if (animationFrameRef.current !== null) cancelAnimationFrame(animationFrameRef.current); }; }, [router]);
  useEffect(() => { if (preferences.autoScroll && (messages.length > 0 || isTyping)) chatRef.current?.scrollTo({ top: chatRef.current.scrollHeight, behavior: "smooth" }); }, [messages, isTyping, preferences.autoScroll]);
  async function startNewChat() { if (isTyping) return; setCurrentChatId(null); setMessages([]); setMessage(""); setSelectedFeature(null); setMode("chat"); setMobileSidebarOpen(false); setLogoFormationKey((key) => key + 1); }
  async function selectChat(id: string) { const user = auth.currentUser; if (!user || isTyping) return; const target = chats.find((chat) => chat.id === id); setMobileSidebarOpen(false); if (target?.kind === "study") { router.push(`/study-v2?chat=${encodeURIComponent(id)}`); return; } setSelectedFeature(null); try { const loadedMessages = await loadMessages(user.uid, id); setCurrentChatId(id); setMessages(loadedMessages.map(({ role, text }) => ({ role, text }))); setMode("chat"); } catch (error) { console.error("Failed to load chat", error); } }
  async function removeChat(id: string) { const user = auth.currentUser; if (!user || isTyping) return; try { await deleteChat(user.uid, id); const remaining = chats.filter((chat) => chat.id !== id); setChats(remaining); if (currentChatId === id) { setCurrentChatId(null); setMessages([]); } } catch (error) { console.error("Failed to delete chat", error); } }
  async function renameConversation(id: string, title: string) { const user = auth.currentUser; if (!user || isTyping) return; try { const cleanTitle = title.replace(/\s+/g, " ").trim().slice(0, 80); if (!cleanTitle) return; await renameChat(user.uid, id, cleanTitle); setChats((prev) => prev.map((chat) => chat.id === id ? { ...chat, title: cleanTitle } : chat)); } catch (error) { console.error("Failed to rename chat", error); } }
  function animateResponse(fullText: string, sources: Source[] = []) { const words = fullText.split(/(\s+)/); const wordsPerSecond = preferences.speed === "normal" ? 45 : 70; const startedAt = performance.now(); setMessages((prev) => [...prev, { role: "ai", text: "", sources }]); const frame = (now: number) => { const visibleWords = Math.min(words.length, Math.floor(((now - startedAt) / 1000) * wordsPerSecond)); const visibleText = words.slice(0, visibleWords).join(""); setMessages((prev) => { const next = [...prev]; if (next.length) next[next.length - 1] = { role: "ai", text: visibleText, sources }; return next; }); if (visibleWords < words.length) animationFrameRef.current = requestAnimationFrame(frame); else { animationFrameRef.current = null; setIsTyping(false); } }; animationFrameRef.current = requestAnimationFrame(frame); }
  async function sendMessage(attachments: Attachment[] = [], overrideText?: string) { const user = auth.currentUser; const userText = (overrideText ?? message).trim(); if (!user || (!userText && attachments.length === 0) || isTyping || !userReady) return; setLastError(null); setMessage(""); const activeFeature = selectedFeature; setSelectedFeature(null); const previousMessages = messages; let chatId = currentChatId; const firstMessage = !chatId || previousMessages.length === 0; const attachmentLabel = attachments.length === 1 ? (attachments[0].type.startsWith("image/") ? "Image" : "PDF") : `${attachments.length} attachments`; const historyText = userText || attachmentLabel; try { if (!chatId) { chatId = await createChat(user.uid, makeTitle(historyText)); setCurrentChatId(chatId); } else if (firstMessage) { await updateChatPreview(user.uid, chatId, historyText, makeTitle(userText || historyText)); setChats((prev) => prev.some((chat) => chat.id === chatId) ? prev.map((chat) => chat.id === chatId ? { ...chat, title: makeTitle(userText || historyText), preview: historyText } : chat) : [{ id: chatId as string, title: makeTitle(userText || historyText), preview: historyText }, ...prev]); } const activeChatId = chatId; if (!activeChatId) throw new Error("Unable to create or select a chat"); await saveMessage(user.uid, activeChatId, "user", historyText); setMessages((prev) => [...prev, { role: "user", text: userText, attachments: attachments.map(({ name, type }) => ({ name, type, dataUrl: "" })) }]); setIsTyping(true); const res = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: userText, history: previousMessages, featureId: activeFeature?.id ?? null, attachments, preferences, mode }) }); const data = await res.json().catch(() => ({})); if (!res.ok || typeof data.reply !== "string") throw new Error(data.error || "AI request failed"); const fullText = data.reply.trim(); await saveMessage(user.uid, activeChatId, "ai", fullText); setChats((prev) => { const existing = prev.find((chat) => chat.id === activeChatId); const updated: ChatSummary = existing ? { ...existing, preview: fullText } : { id: activeChatId, title: makeTitle(historyText), preview: fullText }; return [updated, ...prev.filter((chat) => chat.id !== activeChatId)]; }); animateResponse(fullText, Array.isArray(data.sources) ? data.sources : []); } catch (error) { console.error("Chat error", error); setIsTyping(false); setLastError(error instanceof Error ? error.message : "I couldn't complete that request."); setMessages((prev) => [...prev, { role: "ai", text: "I couldn't complete that request." }]); } }
  async function logout() { try { await signOut(auth); router.replace("/login"); } catch (error) { console.error("Logout failed", error); } }
  const openStudyRoom = () => router.push("/study-v2");
  return <>{userReady && <LogoFormation playKey={logoFormationKey}/>}<div className="tablet-mobile-shell lg:hidden h-[100dvh] w-screen overflow-hidden"><MobileLayout><MobileHeader onMenu={() => setMobileSidebarOpen(true)} onSettings={() => router.push("/settings")} /><div ref={chatRef} className={`min-h-0 flex-1 ${messages.length === 0 && !selectedFeature ? "overflow-hidden" : "overflow-y-auto overscroll-contain pb-24"}`}>{messages.length === 0 && !selectedFeature ? <MobileWelcome onFeatureSelect={setSelectedFeature} onStudyRoom={openStudyRoom} /> : messages.length === 0 ? <div className="h-full bg-black"/> : <div className="flex flex-col gap-5 px-4 pt-6 pb-36">{messages.map((msg, index) => <ChatBubble key={`${msg.role}-${index}`} role={msg.role} text={msg.text} attachments={msg.attachments} sources={msg.sources} />)}{isTyping && messages[messages.length - 1]?.role === "user" && <TypingIndicator/>}{lastError && <button onClick={() => { setLastError(null); void sendMessage(); }} className="self-center rounded-xl border border-red-400/20 bg-red-500/[.06] px-3 py-2 text-[11px] text-red-200">Retry</button>}</div>}</div><FeatureInput feature={selectedFeature} value={message} onChange={setMessage} onSend={sendMessage} onClearFeature={() => setSelectedFeature(null)} mode={mode} onModeChange={setMode} disabled={!userReady || isTyping}/><MobileSidebar open={mobileSidebarOpen} onClose={() => setMobileSidebarOpen(false)} chats={chats} currentChatId={currentChatId} onNewChat={startNewChat} onSelectChat={selectChat} onDeleteChat={removeChat} onRenameChat={renameConversation} onLogout={logout}/></MobileLayout></div><main className="hidden h-[100dvh] min-h-0 overflow-hidden bg-black lg:flex lg:flex-row"><div className="hidden h-full shrink-0 lg:block lg:w-[264px]"><Sidebar onNewChat={startNewChat} chats={chats} currentChatId={currentChatId} onSelectChat={selectChat} onDeleteChat={removeChat}/></div><section className="flex min-h-0 min-w-0 flex-1 flex-col bg-black"><Header/><div ref={chatRef} className={`min-h-0 flex-1 overflow-y-auto overscroll-contain px-4 py-6 sm:px-6 lg:px-10 ${messages.length === 0 ? "overflow-hidden" : ""}`}><div className="mx-auto w-full max-w-4xl">{messages.length === 0 ? <div className="h-full min-h-0"><MobileWelcome onFeatureSelect={setSelectedFeature} onStudyRoom={openStudyRoom} /></div> : <div className="space-y-6">{messages.map((msg, index) => <ChatBubble key={`${msg.role}-${index}`} role={msg.role} text={msg.text} attachments={msg.attachments} sources={msg.sources} />)}{isTyping && messages[messages.length - 1]?.role === "user" && <TypingIndicator/>}</div>}</div></div><footer className="shrink-0 border-t border-white/[.08] bg-black px-4 py-4 sm:px-6 lg:px-10"><DesktopComposer feature={selectedFeature} value={message} onChange={setMessage} onSend={sendMessage} onClearFeature={() => setSelectedFeature(null)} mode={mode} onModeChange={setMode} disabled={!userReady || isTyping}/></footer></section></main></>;
}
