"use client";

import { useRef, useState } from "react";
import { ArrowUp, Camera, FileText, ImagePlus, Plus, X, Search, BookOpen, Code2, Eye, PenLine, Sparkles } from "lucide-react";
import { processAttachmentFiles, type Attachment, type SelectedFeature } from "@/components/mobile/FeatureInput";
import { THEON_MODES, type TheonMode } from "@/lib/theon-modes";

type Props = { feature: SelectedFeature | null; value: string; onChange: (value: string) => void; onSend: (attachments: Attachment[]) => void; onClearFeature: () => void; mode: TheonMode; onModeChange: (mode: TheonMode) => void; disabled?: boolean };
const icons = { chat: Sparkles, web: Search, research: Search, study: BookOpen, code: Code2, vision: Eye, write: PenLine };

export default function DesktopComposer({ feature, value, onChange, onSend, onClearFeature, mode, onModeChange, disabled = false }: Props) {
  const cameraRef = useRef<HTMLInputElement>(null); const galleryRef = useRef<HTMLInputElement>(null); const pdfRef = useRef<HTMLInputElement>(null); const [attachments, setAttachments] = useState<Attachment[]>([]); const [picker, setPicker] = useState(false); const [modePicker, setModePicker] = useState(false); const [processing, setProcessing] = useState(false); const [error, setError] = useState("");
  async function choose(files: FileList | null) { if (!files) return; setPicker(false); setError(""); setProcessing(true); try { const next = await processAttachmentFiles(Array.from(files)); setAttachments((old) => [...old, ...next].slice(0, 4)); } catch (e) { setError(e instanceof Error ? e.message : "Could not process attachment."); } finally { setProcessing(false); } }
  const canSend = !disabled && !processing && (!!value.trim() || attachments.length > 0);
  function send() { if (!canSend) return; const files = attachments; setAttachments([]); onSend(files); }
  const ModeIcon = icons[mode];
  return <div className="relative mx-auto w-full max-w-4xl">
    <div className="mb-2 flex min-w-0 items-center gap-2 overflow-hidden">
      {feature && <div className="flex min-w-0 max-w-[280px] shrink-0 items-center gap-2 rounded-xl border border-violet-400/20 bg-white/[.03] px-3 py-2 text-xs text-white/70"><span className="truncate">{feature.label}</span><button type="button" onClick={onClearFeature} aria-label="Clear feature" className="shrink-0 text-white/35 hover:text-white"><X size={13}/></button></div>}
      <div className="flex min-w-0 gap-2 overflow-x-auto pb-0.5">{attachments.map((file, i) => <button type="button" key={`${file.name}-${i}`} onClick={() => setAttachments((old) => old.filter((_, n) => n !== i))} className="flex shrink-0 items-center gap-1.5 rounded-xl border border-white/10 bg-white/[.03] px-2.5 py-2 text-[10px] text-white/60"><span>{file.type === "application/pdf" ? "📄 PDF" : "🖼 Image"}</span><X size={11}/></button>)}</div>
    </div>
    {error && <p className="mb-2 text-xs text-red-300" role="alert">{error}</p>}
    {modePicker && <div className="absolute bottom-20 left-0 right-0 z-40 overflow-x-auto rounded-2xl border border-white/10 bg-[#0b0b0b]/98 p-1.5 shadow-2xl backdrop-blur-2xl"><div className="flex min-w-max gap-1">{THEON_MODES.map((item) => { const Icon = icons[item.id]; return <button type="button" key={item.id} onClick={() => { onModeChange(item.id); setModePicker(false); }} className={`flex min-w-[150px] items-center gap-2 rounded-xl px-3 py-2.5 text-left ${mode === item.id ? "bg-white/[.08] text-white" : "text-white/55 hover:bg-white/[.05]"}`}><Icon size={16}/><span className="min-w-0"><span className="block truncate text-xs font-medium">{item.label}</span><span className="block truncate text-[9px] text-white/25">{item.description}</span></span></button>; })}</div></div>}
    {picker && <div className="absolute bottom-16 left-0 z-40 flex gap-2 rounded-2xl border border-white/10 bg-[#0b0b0b] p-2 shadow-2xl"><button type="button" onClick={() => cameraRef.current?.click()} className="flex w-20 flex-col items-center gap-1 rounded-xl p-3 text-[10px] text-white/65 hover:bg-white/[.06]"><Camera size={19}/>Camera</button><button type="button" onClick={() => galleryRef.current?.click()} className="flex w-20 flex-col items-center gap-1 rounded-xl p-3 text-[10px] text-white/65 hover:bg-white/[.06]"><ImagePlus size={19}/>Gallery</button><button type="button" onClick={() => pdfRef.current?.click()} className="flex w-20 flex-col items-center gap-1 rounded-xl p-3 text-[10px] text-white/65 hover:bg-white/[.06]"><FileText size={19}/>PDF</button></div>}
    <input ref={cameraRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={(e) => { void choose(e.target.files); e.currentTarget.value=""; }}/><input ref={galleryRef} type="file" accept="image/*" multiple className="hidden" onChange={(e) => { void choose(e.target.files); e.currentTarget.value=""; }}/><input ref={pdfRef} type="file" accept="application/pdf,.pdf" multiple className="hidden" onChange={(e) => { void choose(e.target.files); e.currentTarget.value=""; }}/>
    <div className="mb-1 flex items-center justify-between"><button type="button" onClick={() => setModePicker((v) => !v)} className="flex shrink-0 items-center gap-2 rounded-full border border-white/[.09] bg-white/[.035] px-3 py-1.5 text-[10px] text-white/50"><ModeIcon size={12}/>{THEON_MODES.find((item) => item.id === mode)?.label}</button><span className="truncate pl-2 text-[9px] text-white/20">{mode === "research" ? "Multiple sources" : mode === "web" ? "Current web" : mode === "study" ? "Deep + simple" : "Theon AI"}</span></div>
    <form onSubmit={(event) => { event.preventDefault(); send(); }} noValidate autoComplete="off" className="flex min-w-0 gap-2">
      <button type="button" onClick={() => setPicker((v) => !v)} disabled={disabled || processing} aria-label="Add attachment" className="flex h-14 w-14 shrink-0 items-center justify-center rounded-[22px] border border-white/[.11] bg-white/[.035] text-white/65 hover:text-white disabled:opacity-40"><Plus size={21}/></button>
      <input value={value} onChange={(e) => onChange(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder={processing ? "Reading PDF..." : feature ? `Add context for ${feature.label}...` : mode === "web" ? "Search the web with Theon..." : mode === "research" ? "Ask for deep research..." : "Ask Theon anything..."} disabled={disabled || processing} className="h-14 min-w-0 flex-1 rounded-[22px] border border-white/[.11] bg-white/[.035] px-5 text-[15px] text-white outline-none placeholder:text-white/25 focus:border-violet-400/35"/>
      <button type="submit" disabled={!canSend} aria-label="Send message" className="flex h-14 w-14 shrink-0 items-center justify-center rounded-[22px] bg-gradient-to-r from-violet-600 to-cyan-500 text-white disabled:opacity-30"><ArrowUp size={21}/></button>
    </form>
    {attachments.some((f) => f.type === "application/pdf") && <p className="mt-1.5 text-center text-[9px] text-white/25">🔒 This PDF is used for this analysis and isn&apos;t saved to your chat history.</p>}
  </div>;
}
