"use client";

import Image from "next/image";
import { BookOpen, ChevronDown, Command, LogOut, Moon, Settings, Sun, UserRound } from "lucide-react";
import { signOut } from "firebase/auth";
import { auth } from "@/lib/firebase";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import CommandPalette from "@/components/CommandPalette";

export default function Header() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false); const [theme, setTheme] = useState<"dark" | "light">("dark"); const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const saved = localStorage.getItem("theon-theme"); if (saved === "light" || saved === "dark") { setTheme(saved); document.documentElement.classList.toggle("light", saved === "light"); } const close = (event: MouseEvent) => { if (menuRef.current && !menuRef.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  function changeTheme(value: "dark" | "light") { setTheme(value); localStorage.setItem("theon-theme", value); document.documentElement.classList.toggle("light", value === "light"); setOpen(false); }
  async function logout() { await signOut(auth); router.push("/login"); }
  const user = auth.currentUser; const name = user?.displayName || user?.email?.split("@")[0] || "Theon account";
  const newChat = () => router.push("/");
  const research = () => { localStorage.setItem("theon-command-mode", "research"); router.push("/"); };
  return <><CommandPalette open={commandOpen} onClose={() => setCommandOpen(false)} onNewChat={newChat} onStudy={() => router.push("/study-v2")} onResearch={research} onSettings={() => router.push("/settings")} /><header className="relative z-30 flex h-[72px] shrink-0 items-center justify-between border-b border-white/[.08] px-5 sm:px-7">
    <div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-[14px] border border-cyan-200/10 bg-white/[.035]"><Image src="/logo.png" alt="Theon AI" width={34} height={34} priority className="h-8 w-8 object-contain"/></div><div className="leading-tight"><div className="flex items-center gap-2"><h2 className="text-[14px] font-semibold tracking-[-.01em] text-white">Theon AI</h2><span className="rounded-full border border-cyan-200/15 bg-cyan-300/[.05] px-1.5 py-0.5 text-[7px] font-semibold uppercase tracking-[.16em] text-cyan-200/65">Workspace</span></div><p className="mt-1 text-[9px] text-white/25">Intelligent tools, one place</p></div></div>
    <div className="hidden items-center gap-2 sm:flex"><button onClick={() => setCommandOpen(true)} className="flex items-center gap-2 rounded-full border border-white/[.08] bg-white/[.025] px-3 py-2 text-[10px] font-medium text-white/45 hover:border-violet-300/20 hover:text-violet-100"><Command size={13}/> Command <kbd className="rounded-md border border-white/10 px-1.5 py-0.5 text-[8px] text-white/20">⌘K</kbd></button><button onClick={() => router.push("/study-v2")} className="flex items-center gap-2 rounded-full border border-white/[.08] bg-white/[.025] px-3 py-2 text-[10px] font-medium text-white/55 hover:border-cyan-200/20 hover:text-cyan-100"><BookOpen size={13}/> Study Room</button><div className="h-5 w-px bg-white/[.08]"/></div>
    <div ref={menuRef} className="relative"><button onClick={() => setOpen((value) => !value)} aria-label="Open profile menu" aria-expanded={open} className="flex h-10 items-center gap-2 rounded-full border border-white/[.09] bg-white/[.035] px-2.5 text-white/65 hover:border-cyan-200/20 hover:text-white"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-br from-cyan-300 to-blue-500 text-[10px] font-bold text-[#06121b]">{name[0]?.toUpperCase()}</span><ChevronDown size={13}/></button>{open && <div className="absolute right-0 top-12 w-64 overflow-hidden rounded-2xl border border-cyan-200/10 bg-[#091726]/95 p-2 shadow-2xl shadow-black/50 backdrop-blur-2xl"><button onClick={() => router.push("/profile")} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-cyan-300/[.06]"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-cyan-300 to-blue-500 text-sm font-bold text-[#06121b]">{name[0]?.toUpperCase()}</div><div className="min-w-0"><p className="truncate text-xs font-medium text-white/85">{name}</p><p className="truncate text-[10px] text-white/30">{user?.email}</p></div></button><div className="my-1 h-px bg-white/[.07]"/><button onClick={() => router.push("/profile")} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs text-white/55 hover:bg-white/[.05]"><UserRound size={15}/> Profile</button><button onClick={() => router.push("/settings")} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs text-white/55 hover:bg-white/[.05]"><Settings size={15}/> Settings</button><div className="px-1"><p className="px-2 py-1.5 text-[9px] uppercase tracking-[.16em] text-white/20">Appearance</p><div className="grid grid-cols-2 gap-1"><button onClick={() => changeTheme("dark")} className={`flex items-center justify-center gap-1.5 rounded-lg py-2 text-[10px] ${theme === "dark" ? "bg-cyan-300/10 text-cyan-100" : "text-white/35"}`}><Moon size={12}/>Dark</button><button onClick={() => changeTheme("light")} className={`flex items-center justify-center gap-1.5 rounded-lg py-2 text-[10px] ${theme === "light" ? "bg-cyan-300/10 text-cyan-900" : "text-white/35"}`}><Sun size={12}/>Light</button></div></div><button onClick={logout} className="mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs text-red-300/70 hover:bg-red-400/10"><LogOut size={15}/> Log out</button></div>}</div>
  </header></>;
}
