"use client";

import { BookOpen, MessageSquare, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import type { ChatSummary } from "@/lib/chat-history";

type SidebarProps = { onNewChat: () => void; chats: ChatSummary[]; currentChatId: string | null; onSelectChat: (id: string) => void; onDeleteChat: (id: string) => void; };

export default function Sidebar({ onNewChat, chats, currentChatId, onSelectChat }: SidebarProps) {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => chats.filter((chat) => `${chat.title} ${chat.preview || ""}`.toLowerCase().includes(query.toLowerCase())), [chats, query]);
  function select(chat: ChatSummary) {
    if (chat.kind === "study") { window.location.href = `/study?chat=${encodeURIComponent(chat.id)}`; return; }
    onSelectChat(chat.id);
  }
  return <aside className="relative flex h-full w-[264px] shrink-0 flex-col overflow-hidden border-r border-white/[0.08] bg-black p-4"><div className="pointer-events-none absolute -left-24 top-24 h-64 w-64 rounded-full bg-violet-600/[0.035] blur-3xl"/><div className="pointer-events-none absolute -right-28 bottom-10 h-56 w-56 rounded-full bg-cyan-500/[0.025] blur-3xl"/><div className="relative z-10 mb-5 px-2"><h1 className="text-[17px] font-semibold tracking-[-0.02em] text-white">Theon AI</h1><p className="mt-1 text-[10px] tracking-wide text-white/30">Chat history</p></div><button onClick={onNewChat} className="relative z-10 mb-3 flex h-11 w-full items-center justify-center gap-2 rounded-2xl border border-white/[0.11] bg-white/[0.045] text-sm font-medium text-white/85 transition hover:bg-white/[0.07] active:scale-[0.985]"><Plus size={17}/> New chat</button><div className="relative z-10 mb-3 flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.025] px-3 py-2"><Search size={15} className="text-white/25"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search chats" className="min-w-0 flex-1 bg-transparent text-xs text-white outline-none placeholder:text-white/25"/></div><div className="relative z-10 mb-2 px-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-white/25">History</div><div className="relative z-10 min-h-0 flex-1 space-y-1 overflow-y-auto pr-1">{filtered.length === 0 ? <p className="px-2 py-4 text-xs leading-5 text-white/25">{query ? "No matching conversations." : "Your conversations will appear here."}</p> : filtered.map((chat) => <button key={chat.id} onClick={() => select(chat)} className={`flex w-full min-w-0 items-center gap-3 rounded-2xl border px-3.5 py-3 text-left transition duration-100 ${currentChatId === chat.id ? "border-white/[0.09] bg-white/[0.07] text-white" : "border-transparent text-white/55 hover:bg-white/[0.045] hover:text-white/80"}`}>{chat.kind === "study" ? <BookOpen size={16} className="shrink-0 text-violet-300/70"/> : <MessageSquare size={16} className="shrink-0 opacity-55"/>}<span className="min-w-0 flex-1"><span className="flex items-center gap-1.5 truncate text-[13px] font-medium"><span className="truncate">{chat.title}</span>{chat.kind === "study" && <span className="shrink-0 rounded-full bg-violet-400/10 px-1.5 py-0.5 text-[8px] uppercase tracking-wider text-violet-300/70">Study</span>}</span>{chat.preview && <span className="mt-0.5 block truncate text-[10px] text-white/25">{chat.preview}</span>}</span></button>)}</div></aside>;
}
