"use client";

import { BookOpen, Clock3, MessageSquare, Plus, Search, Settings, Sparkles, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import type { ChatSummary } from "@/lib/chat-history";

type SidebarProps = { onNewChat: () => void; chats: ChatSummary[]; currentChatId: string | null; onSelectChat: (id: string) => void; onDeleteChat: (id: string) => void; };
export default function Sidebar({ onNewChat, chats, currentChatId, onSelectChat }: SidebarProps) {
  const [query, setQuery] = useState(""); const filtered = useMemo(() => chats.filter((chat) => `${chat.title} ${chat.preview || ""}`.toLowerCase().includes(query.toLowerCase())), [chats, query]);
  function select(chat: ChatSummary) { if (chat.kind === "study") { window.location.href = `/study-v2?chat=${encodeURIComponent(chat.id)}`; return; } onSelectChat(chat.id); }
  return <aside className="relative flex h-full w-[286px] shrink-0 flex-col overflow-hidden border-r border-white/[.08] p-4">
    <div className="pointer-events-none absolute -left-28 top-16 h-72 w-72 rounded-full bg-cyan-400/[.07] blur-[100px]"/>
    <div className="relative z-10 flex items-center gap-3 px-2 pb-5"><div className="flex h-10 w-10 items-center justify-center rounded-[14px] border border-cyan-200/10 bg-cyan-300/[.04]"><Sparkles size={18} className="text-cyan-200"/></div><div><h1 className="text-[15px] font-semibold text-white">Theon AI</h1><p className="mt-0.5 text-[9px] uppercase tracking-[.17em] text-white/25">Command Center</p></div></div>
    <button onClick={onNewChat} className="relative z-10 mb-2 flex h-11 w-full items-center justify-center gap-2 rounded-2xl border border-cyan-200/15 bg-cyan-300/[.07] text-[12px] font-semibold text-cyan-100 hover:bg-cyan-300/[.12]"><Plus size={16}/> New conversation</button>
    <div className="relative z-10 mb-4 grid grid-cols-2 gap-1.5"><button onClick={onNewChat} className="flex items-center justify-center gap-1.5 rounded-xl border border-white/[.07] bg-white/[.025] py-2 text-[9px] text-white/45 hover:text-cyan-100"><MessageSquare size={12}/> Chat</button><button onClick={() => window.location.href="/study-v2"} className="flex items-center justify-center gap-1.5 rounded-xl border border-white/[.07] bg-white/[.025] py-2 text-[9px] text-white/45 hover:text-cyan-100"><BookOpen size={12}/> Study</button></div>
    <div className="relative z-10 mb-3 flex items-center gap-2 rounded-xl border border-white/[.09] bg-white/[.025] px-3 py-2.5"><Search size={14} className="text-white/25"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search your workspace" className="min-w-0 flex-1 bg-transparent text-[11px] text-white outline-none placeholder:text-white/20"/></div>
    <div className="relative z-10 mb-2 flex items-center justify-between px-2"><span className="flex items-center gap-1.5 text-[9px] font-semibold uppercase tracking-[.19em] text-white/25"><Clock3 size={11}/> Recent</span><span className="text-[8px] text-white/20">{filtered.length}</span></div>
    <div className="relative z-10 min-h-0 flex-1 space-y-1 overflow-y-auto pr-1">{filtered.length === 0 ? <p className="px-2 py-5 text-[10px] leading-5 text-white/25">{query ? "No matching conversations." : "Start a conversation and your workspace history will appear here."}</p> : filtered.map((chat) => <button key={chat.id} onClick={() => select(chat)} className={`group flex w-full min-w-0 items-center gap-3 rounded-2xl border px-3 py-3 text-left transition ${currentChatId === chat.id ? "border-cyan-200/15 bg-cyan-300/[.07] text-white" : "border-transparent text-white/50 hover:bg-white/[.035]"}`}><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-xl ${chat.kind === "study" ? "bg-blue-300/[.08] text-blue-200" : "bg-white/[.04] text-white/35"}`}>{chat.kind === "study" ? <BookOpen size={14}/> : <MessageSquare size={14}/>}</div><span className="min-w-0 flex-1"><span className="flex items-center gap-1.5 truncate text-[11px] font-medium"><span className="truncate">{chat.title}</span>{chat.kind === "study" && <span className="shrink-0 rounded-full bg-blue-300/10 px-1.5 py-0.5 text-[7px] uppercase tracking-wider text-blue-200/70">Study</span>}</span>{chat.preview && <span className="mt-1 block truncate text-[9px] text-white/20">{chat.preview}</span>}</span></button>)}</div>
    <div className="relative z-10 mt-3 grid grid-cols-2 gap-1.5 border-t border-white/[.07] pt-3"><button onClick={() => window.location.href="/profile"} className="flex items-center justify-center gap-1.5 rounded-xl py-2 text-[9px] text-white/35 hover:bg-white/[.04] hover:text-white"><UserRound size={12}/> Profile</button><button onClick={() => window.location.href="/settings"} className="flex items-center justify-center gap-1.5 rounded-xl py-2 text-[9px] text-white/35 hover:bg-white/[.04] hover:text-white"><Settings size={12}/> Settings</button></div>
  </aside>;
}
